[project]
name = "ANCCR"
version = "0.1.0"
description = "Add a short description here"
authors = ["todo <todo@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tasks]
start = "jupyter lab"

[dependencies]
python = ">=3.12.3,<3.13"
numpy = ">=1.26.4,<1.27"
jupyterlab = ">=4.2.2,<4.3"
matplotlib = ">=3.8.4,<3.9"
